project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "FEF3001 Yapay Zekaya Giriş"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa
      - href: about.qmd
        text: Hakkında
      - href: notlar.qmd
        text: Notlar

format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
