# FEF3001 Yapay Zekaya Giriş

## Kaynaklar

- *Makine Öğrenmesinde Sınıflandırma Yöntemleri ve R Uygulamaları*, Ersoy Öz & Selçuk Alp, Nobel Akademik Yayıncılık, 2020.
- *Veri Madenciliği ve Makine Öğrenmesi İle Farklı Alanlarda Uygulamalar*, Şenol Çelik, Nilay Köleoğlu, & Fatih Çemrek, Holistence Publications, 2022
- *Sağlık Bilimlerinde Yapay Zeka*, Ahmet Rıza Şahin, Kamil Doğan, & Süleyman Sivri, Akademisyen Kitabevi A.Ş., 2020
- *Yapay Zeka*, Atınç Yılmaz, Kodlab Yayın Dağıtım Yazılım Ltd. Şti., 2022
- *Machine Learning Algorithms*, Giuseppe Bonaccorso, Packt Publishing, 2017.
- *Optimizasyon Modelleme ve Yapay Zeka Algoritmaları*, Bayram Köse, Bahar Demirtürk, Efe Akademi Yayınları, 2023

## Ders1

*3 Ekim 2024 16:00*

**İçerik**: İlk derste, ChatGPT ve benzeri büyük dil modelleri tanıtıldı. OpenAI Playground üzerinde "cümle tamamlama" kavramı ve "temparature" ayarı gösterildi. Daha iyi çıktı almak için Prompt ayarları anlatıldı. Dökümandan sorgu/chat yapmak için Gemini ve Claude örnekleri verildi. Yine Claude üzerinden kod yazdırma örneği işlendi. [İngilizce Sunum linki](ders1.ipynb)

## Ders2

*10 Ekim 2024 16:00*

**İçerik**: ChatGPT ve ötesi. [İngilizce Sunum linki](ders1.ipynb)

## Ders3

*17 Ekim 2024 16:00*

**İçerik**: Veri türleri ve verilerin işlenmesine dair bilgi verildi. Performans ölçütleri konusuna başlandı. [Sunum linki1](files/Hafta_3_1.pdf) (slayt 24'e kadar) ve [Sunum link2](ders3.qmd)

## Ders4

*24 Ekim 2024 16:00*

**İçerik**: Performans ölçütleri konusuna devam edildi. Optimizasyon konusunda başlandı. [Performans sunum link](ders3.qmd) [Optimizasyon sunum link](files/Hafta_4.pdf)

## Ders5

*31 Ekim 2024 16:00*

**İçerik**: Optimizasyon konusuna devam edildi. [Optimizasyon sunum link](files/Hafta_5.pdf)

## Ders6

*7 Kasım 2024 16:00*

**İçerik**: Genetik algoritmalar [sunum link](files/Hafta_6.pdf)

## Ders7

*14 Kasım Perşembe 16:00*

**İçerik**: Yapay sinir ağları [Sunum linki](ders7.qmd). Derste kullanılan yapay sinir ağı demo sayfaları için [link1](https://ml-playground.com/) ve [link2](https://akarzazi.github.io/neural-network-playground/)
